name: openai_server
description: "server side"
version: 1.0.0+1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  dotenv: ^4.0.1
  http: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
